spring.application.name=SpringBootAPI


spring.datasource.url=jdbc:postgresql://localhost:5432/springdb
spring.datasource.username=ejemplo
spring.datasource.password=example
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

jwt.secret=7c0c0c5d7e317f9f14f849246400364c919be3be2bad1294d90daad1fdf777f6
jwt.expiration=86400000