spring.application.name=SpringBootAPI


spring.datasource.url=jdbc:postgresql://localhost:5432/springdb
#  OJO AQUÍ: Deben ser los mismos de tu docker-compose
spring.datasource.username=ejemplo
spring.datasource.password=example
spring.datasource.driver-class-name=org.postgresql.Driver


# 2. Configuración de Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# 3. Mostrar consultas SQL en consola
spring.jpa.show-sql=true